image: registry.gitlab.com/cape-modeler/frontend:latest


stages:
  - lint
  - test
  - after
  - deploy


lint:
  stage: lint
  before_script:
      - cp -R /app/node_modules .
  script:
      - npm run lint -- --no-fix
  except:
    - electron_ci_deploy

unit:
  stage: test
  before_script:
      - cp -R /app/node_modules .
      - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      - chmod +x ./cc-test-reporter
      - ./cc-test-reporter before-build
  script:
      - npm run test:unit -- --ci
  after_script:
      - ./cc-test-reporter after-build
  artifacts:
      paths:
        - coverage
  except:
    - electron_ci_deploy

e2e:
  stage: test
  before_script:
      - cp -R /app/node_modules .
  script:
      - npm run test:e2e -- --headless --record --key $CYPRESS_RECORD_KEY
  except:
    - electron_ci_deploy

pages:
  stage: deploy
  before_script:
    - cp -R /app/node_modules .
  script:
    - npm run build
    - mv public public-vue # GitLab Pages hooks on the public folder
    - mv dist public # rename the dist folder (result of npm run build)
  artifacts:
    paths:
      - public
  only:
    - tags

electron:
  stage: deploy
  before_script:
    - cp -R /app/node_modules .
    - wget https://blog.anantshri.info/content/uploads/2010/09/add-apt-repository.sh.txt
    - cp add-apt-repository.sh.txt /usr/sbin/add-apt-repository
    - chmod o+x /usr/sbin/add-apt-repository
    - add-apt-repository ppa:ubuntu-wine/ppa
    - apt-get update
    - apt-get install -y wine1.7 winetricks
    - wine --version
  script:
    - npm run electron:build -- -p always -mwl
  artifacts:
    paths:
      - dist_electron
  only:
    - tags
    - electron_ci_deploy