image: registry.gitlab.com/cape-modeler/frontend:latest

pages:
  before_script:
    - cp -R /app/node_modules .
  script:
    - npm run build
    - mv public public-vue # GitLab Pages hooks on the public folder
    - mv dist public # rename the dist folder (result of npm run build)
  artifacts:
    paths:
      - public
  only:
    - tags
