image: registry.gitlab.com/cape-modeler/frontend:latest


stages:
  - lint
  - test
  - quality
  - deploy


lint:
  stage: lint
  before_script:
      - cp -R /app/node_modules .
  script:
      - npm run lint -- --no-fix

unit:
  stage: test
  before_script:
      - cp -R /app/node_modules .
  script:
      - npm run test:unit -- --ci
  artifacts:
      paths:
        - coverage

e2e:
  stage: test
  before_script:
      - cp -R /app/node_modules .
  script:
      - npm run test:e2e -- --headless --record --key $CYPRESS_RECORD_KEY

pages:
  stage: deploy
  before_script:
    - cp -R /app/node_modules .
  script:
    - npm run build
    - mv public public-vue # GitLab Pages hooks on the public folder
    - mv dist public # rename the dist folder (result of npm run build)
  artifacts:
    paths:
      - public
  only:
    - tags

code_quality:
  image: docker:stable
  stage: quality
  variables:
    DOCKER_DRIVER: overlay2
  allow_failure: true
  services:
    - docker:stable-dind
  script:
    - export SP_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')
    - docker run
        --env SOURCE_CODE="$PWD"
        --volume "$PWD":/code
        --volume /var/run/docker.sock:/var/run/docker.sock
        "registry.gitlab.com/gitlab-org/security-products/codequality:$SP_VERSION" /code
  artifacts:
    reports:
      codequality: [gl-code-quality-report.json]
