describe('Context Factors Page', () => {
  before(() => {
    cy.setupSampleData()
  })
  beforeEach(() => {
    cy.visit('/context_factors')
  })
  it('renders the tree', () => {
    cy.get('.el-tree')
    cy.get('[style="padding-left: 0px;"] > .custom-tree-node > :nth-child(2)').contains('Pizza Donalds')
  })
  it('can collapse nodes', () => {
    cy.get('.el-tree').contains('Temperature Sensor')
    cy.get(':nth-child(2) > :nth-child(1) > .el-tree-node__content > .custom-tree-node > :nth-child(2)').should('be.visible')
    cy.get('[style="padding-left: 0px;"] > .custom-tree-node > :nth-child(2)').click()
    cy.get(':nth-child(2) > :nth-child(1) > .el-tree-node__content > .custom-tree-node > :nth-child(2)').should('not.be.visible')
  })
  it('can filter the context factors', () => {
    cy.get(':nth-child(1) > [style="padding-left: 18px;"] > .custom-tree-node > :nth-child(2)').should('be.visible')
    cy.get('.el-col > .el-input > .el-input__inner').type('Do')
    cy.get(':nth-child(1) > [style="padding-left: 18px;"] > .custom-tree-node > :nth-child(2)').should('not.be.visible')
  })
  it('can add a context factor', () => {
    cy.get('.el-form-item__content > .el-input > .el-input__inner').type('New CF')
    cy.wait(300)
    cy.get('.el-form > .el-button').click()
    cy.wait(300)
    cy.url().should('contain', Cypress.config().baseUrl + '/context_factors/')
    cy.url().should('contain', 'edit')
    cy.get('.el-button--success').click()
    cy.get('[style="padding-left: 0px;"] > .custom-tree-node > :nth-child(2)').contains('New CF')
  })
  it('can edit a context factor', () => {
    cy.get('[style="padding-left: 0px;"] > .custom-tree-node > .align-right > .el-button').first().click()
    cy.url().should('contain', Cypress.config().baseUrl + '/context_factors/')
    cy.url().should('contain', 'edit')
    cy.get('.el-dialog__body > .el-row > .el-col > .el-form > .is-required > .el-form-item__content > .el-input > .el-input__inner').type(' new')
    cy.get('.less-margin-top > .el-col > .el-form > .el-button').click()
    cy.get(':nth-child(4) > .el-form > :nth-child(1) > .el-form-item__content > .el-input > .el-input__inner').type('Foo')
    cy.get(':nth-child(4) > .el-form > :nth-child(2) > :nth-child(1) > .el-form > .el-form-item > .el-form-item__content > .input-with-select > [placeholder="Value"]').type('Bar')
    const select = cy.get('.el-select').first()
    select.find('.el-input > .el-input__inner').click()
    cy.get('.el-select-dropdown .el-scrollbar__view').eq(5).find(':nth-child(2) > span').click()
    cy.get('.el-button--success').click()
    cy.url().should('eq', Cypress.config().baseUrl + '/context_factors')
    cy.get('[style="padding-left: 0px;"] > .custom-tree-node > :nth-child(2)').contains('Pizza Donalds new')
    cy.get('[style="padding-left: 0px;"] > .custom-tree-node > .fa').should('have.class', 'fa-thermometer-full')
  })
  it('can remove a context factor', () => {
    cy.get('.custom-tree-node').should('have.length', 8)
    cy.get('[style="padding-left: 0px;"] > .custom-tree-node > .align-right > .el-button').first().click()
    cy.get('#left-align > :nth-child(2)').click()
    cy.get('.el-button--primary > span').click()
    cy.url().should('contain', Cypress.config().baseUrl + '/context_factors')
    cy.get('.custom-tree-node').should('have.length', 7)
  })
})
