describe('Context Factors Page', () => {
  before(() => {
    cy.setupSampleData()
  })
  beforeEach(() => {
    cy.visit('/context_factors')
  })
  it('renders the tree', () => {
    cy.get('.el-tree')
    cy.get('[style="padding-left: 0px;"] > .custom-tree-node > :nth-child(2)').contains('Pizza Donalds')
  })
  it('can collapse nodes', () => {
    cy.get('.el-tree').contains('Temperature Sensor')
    cy.get(':nth-child(2) > :nth-child(1) > .el-tree-node__content > .custom-tree-node > :nth-child(2)').should('be.visible')
    cy.get('[style="padding-left: 0px;"] > .custom-tree-node > :nth-child(2)').click()
    cy.get(':nth-child(2) > :nth-child(1) > .el-tree-node__content > .custom-tree-node > :nth-child(2)').should('not.be.visible')
  })
  it('can filter the context factors', () => {
    cy.get(':nth-child(1) > [style="padding-left: 18px;"] > .custom-tree-node > :nth-child(2)').should('be.visible')
    cy.get('.el-col > .el-input > .el-input__inner').type('Do')
    cy.get(':nth-child(1) > [style="padding-left: 18px;"] > .custom-tree-node > :nth-child(2)').should('not.be.visible')
  })
  it('can add a context factor', () => {
    cy.get('.el-form-item__content > .el-input > .el-input__inner').type('New CF')
    cy.wait(300)
    cy.get('.el-form > .el-button').click()
    cy.wait(300)
    cy.url().should('contain', Cypress.config().baseUrl + '/context_factors/')
    cy.url().should('contain', 'edit')
    cy.get('.el-button--success').eq(1).click()
    cy.get('[style="padding-left: 0px;"] > .custom-tree-node > :nth-child(2)').contains('New CF')
  })
  it.only('can edit a context factor', () => {
    cy.get(':nth-child(2) > :nth-child(2) > .el-tree-node__content > .custom-tree-node > .align-right > .el-button').first().click()
    cy.url().should('contain', Cypress.config().baseUrl + '/context_factors/')
    cy.url().should('contain', 'edit')
    cy.get('.less-margin-top > .el-col > .el-form--label-top > :nth-child(1) > .el-form-item__content > .el-input > .el-input__inner').type(' new')
    cy.get('.less-margin-top > .el-col > .el-form--label-top > .el-button--default').click()
    cy.get('.el-select').eq(1).find('.el-input > .el-input__inner').click()
    cy.get('.el-scrollbar > .el-select-dropdown__wrap > .el-scrollbar__view > :nth-child(2) > span').eq(1).click()
    cy.get('.el-form--inline > .is-required > .el-form-item__content > .el-input > .el-input__inner').eq(1).type('Foo')
    cy.get('[placeholder="Value"]').type('11')
    cy.get('.el-form-item__content > .el-select > .el-input > .el-input__suffix > .el-input__suffix-inner > .el-select__caret').click()
    cy.wait(300)
    cy.get('.el-scrollbar > .el-select-dropdown__wrap > .el-scrollbar__view > :nth-child(2)').eq(1).click()

    const select = cy.get('.el-select').first()
    select.find('.el-input > .el-input__inner').click()
    cy.get('.el-select-dropdown .el-scrollbar__view').eq(1).find(':nth-child(2) > span').click()
    cy.get('.el-button--success').eq(0).click()
    cy.wait(1000)
    cy.get('#tab-1').click()

    cy.get('.has-gutter > tr > .el-table_1_column_1 > .cell').contains('Foo')
    cy.get('.input > .el-input__inner').type('NEw State')
    cy.get('.el-form-item__content > .el-button').click()
    cy.get('.el-table__body-wrapper > .el-table__body > tbody > .el-table__row > .el-table_1_column_1 > .cell > #attribute_cell > .n-in > .n_input > .el-input > .el-input__inner').type('19')
    cy.get('.el-button--success').eq(1).click()
    // CHECK SAVE
    cy.url().should('eq', Cypress.config().baseUrl + '/context_factors')
    cy.get(':nth-child(2) > :nth-child(1) > :nth-child(2) > :nth-child(2) > .el-tree-node__content > .custom-tree-node').contains('Serial Number new')
    cy.get(':nth-child(2) > :nth-child(1) > :nth-child(2) > :nth-child(2) > .el-tree-node__content > .custom-tree-node .fa').should('have.class', 'fa-thermometer-full')
  })
  it('can remove a context factor', () => {
    cy.get('.custom-tree-node').should('have.length', 8)
    cy.get('[style="padding-left: 0px;"] > .custom-tree-node > .align-right > .el-button').first().click()
    cy.get('#left-align > :nth-child(2)').click()
    cy.get('.el-button--primary > span').click()
    cy.url().should('contain', Cypress.config().baseUrl + '/context_factors')
    cy.get('.custom-tree-node').should('have.length', 7)
  })
})
